### ISSUE TITLE
Not working for me today

### ISSUE THREAD

**Issue by AtariBaby** [net00-1/SW-DLT#10]
Hi I realize you’re not working on this for the time being. I find today that SW-DLT is not working for me. Even if I press the app in Siri Shortcuts gallery, it just shows some progress on the circle, about halfway, and doesn’t do anything.

Is that an indication that it’s just no longer functional, or is it possible I need to do something on my end to troubleshoot and resolve?

**Comment by net00-1** [comment]
I will close this issue since the main issue for download issues is this one:

https://github.com/net00-1/SW-DLT/issues/9
