### ISSUE TITLE
mediaURL text matching while sharing from YouTube-App

### ISSUE THREAD

**Issue by akuropka** [net00-1/SW-DLT#13]
While sharing a video directly in the YouTube-App or in Safari I get a toast as below:
![Screenshot 2022-04-28 at 07 00 38](https://user-images.githubusercontent.com/22570574/165680305-94ac55b5-52b9-4f1d-8745-eb1dc85215c4.png)
Clicking "Done" repeats the toast, "Cancel" ends the processing.
If I copy the link to clipboard and call SW-DLT afterwards download works as intended.
iOS 15.5b3 (19F5062g)
SW-DLT 3E15 (02/10/22)

**Comment by net00-1** [comment]
Does this still occur on the latest non-beta version? I could not get it to happen on my device.

**Comment by akuropka** [comment]
@net00-1, thank you for your reply.
Just tried again and it did not happen anymore... seems a glitch anywhere else.
