### ISSUE TITLE
No URL provided 

### ISSUE THREAD

**Issue by reinierrr** [net00-1/SW-DLT#14]
I’m trying to download a YouTube playlist, opened in Shortcuts using a link in the pasteboard to follow the steps. Everything seems to operate as expected, however, after finishing up in the shell it returns back to Shortcuts and it shows ‘No URL provided’

![E8797DA5-CEFC-4155-8D93-50E7C0ECCFDB](https://user-images.githubusercontent.com/2427127/171921222-e46c2c6a-6492-47f6-859e-0853f2d9b0fe.jpeg)

Am I supposed to create a folder in Files app where the Shortcut writes to? I can’t seem to find that in the source code I’m reading in the Shortcuts app.

**Comment by net00-1** [comment]
You don't need to create any folder in Files. Your playlist videos are supposed to be saved on a special directory `$SHORTCUTS`

When the process sends you back to Shortcuts it runs the shortcut with passing the path of your downloaded files. That's how the shortcut it's supposed to find your files.

Seems like you are getting my error message for no input for some reason. Can you share which playlist you tried to download? was it audio or video?

**Comment by reinierrr** [comment]
It was a YouTube playlist, audio only.

I reinstalled the shortcut and managed to get the zip file in preview after returning to shortcuts. 

Great Shortcut you wrote and nice to have an introduction to a-Shell Mini, hadn’t heard about it before.
