### ISSUE TITLE
Last two updates broke the shortcut

### ISSUE THREAD

**Issue by Shadowspear123** [net00-1/SW-DLT#18]
The last two updates cause this error message to show:
“Make sure to pass a valid URL to the Get contents of URL action”

The last version that works is 3E16

This is on ios 14.8

**Comment by net00-1** [comment]
It could be a corrupted copy of the shortcut, can you scroll down to the only `Get Contents of URL` action and capture how it looks?

**Comment by Shadowspear123** [comment]
Did a fresh install from RoutineHub- this is what I’m seeing:

**Comment by Shadowspear123** [comment]
Did a fresh install from Routinehub
This is what I see:
![9399E4A8-36B9-493D-B1CB-DD3EE0E11E2D](https://user-images.githubusercontent.com/50462281/192077612-621f1680-57da-41cb-89dd-1845f755f692.jpeg)

**Comment by net00-1** [comment]
I also confirmed it happens on iOS 14. Can you test if this version is working fine? I built it targeting iOS 13 on jellycuts.

https://www.icloud.com/shortcuts/fd988d68e81448ecbb29d43510c9cd08

**Comment by Shadowspear123** [comment]
This version has the same issue

**Comment by net00-1** [comment]
I pushed an update that fixes it, thanks for reporting!
