### ISSUE TITLE
Tumblr videos problematic

### ISSUE THREAD

**Issue by AtariBaby** [net00-1/SW-DLT#28]
Hi and thanks for all your amazing efforts.

Tumblr videos still prove problematic. Plus I believe they now put an overlay on the videos that it’s mature content. (Although this clip is quite tame)
https://www.tumblr.com/strictlyfavorites/701137988410916864/two-in-the-side-pocket?

**Comment by net00-1** [comment]
Hmm, this is managed completely by yt-dlp, have you added your auth details for tumblr and have updated the shortcut and dependencies? Ways of doing all those on the docs.
