### ISSUE TITLE
Stopped working with YouTube

### ISSUE THREAD

**Issue by Oronhyatekha** [net00-1/SW-DLT#29]
Hey Team,

Unfortunately it stopped working with YouTube due to an Error. I wanted to download the Audio of an YouTube Video and it gets me an error in the MiniShell

**Comment by thiago-dev** [comment]
YouTube does not work for me, too. 
_Tried it for the first time_

Error log 
```

~group]$ Executing Shortcut: cd $SHORTCUTS
python SW_DLT.py https://youtu.be/aoTmaVrQi60 -v 1080 30

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib/python3.11/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/8FB3D47A-F9A9-4749-BC19-349B748ADF76/SW_DLT.py", line 18, in <module>
    import requests
  File "/var/mobile/Containers/Data/Application/DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib/python3.11/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/var/mobile/Containers/Data/Application/DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib/python3.11/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/var/mobile/Containers/Data/Application/DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib/python3.11/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/var/mobile/Containers/Data/Application/DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib/python3.11/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path
  File "/var/mobile/Containers/Data/Application/DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib/python3.11/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/var/mobile/Containers/Data/Application/
DB2F3650-F7CD-4560-8046-93F37AA33FF9/Library/lib
/python3.11/site-packages/charset_normalizer/cd.
py", line 9, in <module>
    from .md import is_suspiciously_successive_r
ange
ImportError: dlopen(/private/var/containers/Bund
le/Application/BAAB34DA-114C-4EEB-A5B3-EEE536864
1CC/a-Shell-mini.app/Frameworks/pythonA-charset_
normalizer.md.framework/pythonA-charset_normaliz
er.md, 0x0002): tried: '/private/var/containers/
Bundle/Application/BAAB34DA-114C-4EEB-A5B3-EEE53
68641CC/a-Shell-mini.app/Frameworks/pythonA-char
set_normalizer.md.framework/pythonA-charset_norm
alizer.md' (errno=2), '/private/preboot/Cryptexe
s/OS/private/var/containers/Bundle/Application/B
AAB34DA-114C-4EEB-A5B3-EEE5368641CC/a-Shell-mini
.app/Frameworks/pythonA-charset_normalizer.md.fr
amework/pythonA-charset_normalizer.md' (errno=2)
, '/private/var/containers/Bundle/Application/BA
AB34DA-114C-4EEB-A5B3-EEE5368641CC/a-Shell-mini.
app/Frameworks/pythonA-charset_normalizer.md.fra
mework/pythonA-charset_normalizer.md' (errno=2),
 '/System/Library/Frameworks/pythonA-charset_nor
malizer.md.framework/pythonA-charset_normalizer.
md' (errno=2, not in dyld cache)

```

iOS Version: 16.2

**Comment by jjisharry** [comment]
I suspect this is likely related to a YouTube change that affects YouTube-dl and yt-dlp. Not sure if package managers have been updated yet.

seems to have been patched on yt-dlp but not in YouTube-dl?

https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611

**Comment by Jitees** [comment]
![17C6B6AF-10B1-4221-8AF1-E79F1891022B](https://user-images.githubusercontent.com/114322100/223061771-9fe88739-5254-4713-b08c-506c2a198065.png)
Similar problem happened to me, these are what happened in aShell half a second before it switch to Shortcut.

**Comment by morby** [comment]
I’ve encountered this issue as well and while I suspect I know the fix, I’ve no idea how to _implement_ the fix. 

According to the yt-dlp GitHub, that uploaded ID issue has been resolved as of the 2023.01.06 version of yt-dlp ([see here](https://github.com/yt-dlp/yt-dlp/issues/6247)) and you can pop into a-shell and type ‘pip install yt-dlp’ to update it.

The problem is that SW-DLT will overwrite the updated yt-dlp installation with the 2022.10.04 version which you can verify by running the pip update, running the SW-DLT shortcut, then returning to a-Shell and entering ‘yt-dlp -U’

![IMG_4494](https://user-images.githubusercontent.com/810916/223119262-2076c5ef-b055-4de7-a344-48efa7d262c3.jpeg)

I _think_ SW-DLT points to a specific Python file on GitHub for its configuration and I imagine that’s what’s pointing at the old version of yt-dlp.

**Comment by net00-1** [comment]
Hi, sorry for not checking the issue.

This error is caused by youtube's addition of username tags. It broke yt-dlp but that has already been fixed there.

The proper way of updating dependencies for use with SW-DLT is [in the docs](https://github.com/net00-1/SW-DLT/blob/master/Docs.md#updating-utilities).

I have already verified updating deps fixes it on iOS 14/15. As said in the PSA, if you keep receiving other errors and are on iOS 16, I can't provide support yet.

**Comment by Jitees** [comment]
> The proper way of updating dependencies for use with SW-DLT is [in the docs](https://github.com/net00-1/SW-DLT/blob/master/Docs.md#updating-utilities).

Great news, it’s back to normal now!

**Comment by jjisharry** [comment]
Updating the dependencies solved the issue - working on iOS 16.2

Thanks @net00-1

**Comment by net00-1** [comment]
I'm gonna leave this issue up since this is being asked frequently

**Comment by alkoka** [comment]
![image](https://user-images.githubusercontent.com/42521808/224835247-6a10dd87-1828-47f4-9446-91419c1d8219.jpeg)

**Comment by alkoka** [comment]
> Have you tried rebooting the device? 

I have just did, deleting dependencies is still not going through.

I tested YouTube via
- The Youtube app and
- VideoLite
but of course they both take the same exact youtu.be link. 

I even wonder what Shortcuts mean by communicating with "the app".

Which app does it have problems with?!?

**Comment by net00-1** [comment]
I think it means that the a-shell commands are failing for some reason. Next thing you should reinstall a-shell and the shortcut. Maybe that works.

**Comment by alkoka** [comment]
**Reinstalled both a-shell mini and the shortcut itself, now I get the following error (yt-dlp url command via a-shell mini works though):**

Traceback (most recent call last):

    import charset_normalizer as chardet
  File "/var/mobile/Containers/Data/Application/3C
BA715F-B54A-4D74-92AE-4AC133AA3C16/Library/lib/pyt
hon3.11/site-packages/charset_normalizer/__init__.
py", line 24, in <module>
    from .api import from_bytes, from_fp, from_pat
h
  File "/var/mobile/Containers/Data/Application/3C
BA715F-B54A-4D74-92AE-4AC133AA3C16/Library/lib/pyt
hon3.11/site-packages/charset_normalizer/api.py", 
line 5, in <module>
    from .cd import (
  File "/var/mobile/Containers/Data/Application/3C
BA715F-B54A-4D74-92AE-4AC133AA3C16/Library/lib/pyt
hon3.11/site-packages/charset_normalizer/cd.py", l
ine 9, in <module>
    from .md import is_suspiciously_successive_ran
ge
ImportError: dlopen(/private/var/containers/Bundle
/Application/4C42D808-A658-4267-AB9C-EAC0B40240DF/
a-Shell-mini.app/Frameworks/pythonA-charset_normal
izer.md.framework/pythonA-charset_normalizer.md, 0
x0002): tried: '/private/var/containers/Bundle/App
lication/4C42D808-A658-4267-AB9C-EAC0B40240DF/a-Sh
ell-mini.app/Frameworks/pythonA-charset_normalizer
.md.framework/pythonA-charset_normalizer.md' (no s
uch file), '/System/Library/Frameworks/pythonA-cha
rset_normalizer.md.framework/pythonA-charset_norma
lizer.md' (no such file)

**Comment by alkoka** [comment]
**UPDATE: a-shell full version works well. **
> **Reinstalled both a-shell mini and the shortcut itself, now I get the following error (yt-dlp url command via a-shell mini works though):**
> 
> Traceback (most recent call last):
> 
>     import charset_normalizer as chardet
>   File "/var/mobile/Containers/Data/Application/3C
> BA715F-B54A-4D74-92AE-4AC133AA3C16/Library/lib/pyt
> hon3.11/site-packages/charset_normalizer/__init__.
> py", line 24, in <module>
>     from .api import from_bytes, from_fp, from_pat
> h
>   File "/var/mobile/Containers/Data/Application/3C
> BA715F-B54A-4D74-92AE-4AC133AA3C16/Library/lib/pyt
> hon3.11/site-packages/charset_normalizer/api.py", 
> line 5, in <module>
>     from .cd import (
>   File "/var/mobile/Containers/Data/Application/3C
> BA715F-B54A-4D74-92AE-4AC133AA3C16/Library/lib/pyt
> hon3.11/site-packages/charset_normalizer/cd.py", l
> ine 9, in <module>
>     from .md import is_suspiciously_successive_ran
> ge
> ImportError: dlopen(/private/var/containers/Bundle
> /Application/4C42D808-A658-4267-AB9C-EAC0B40240DF/
> a-Shell-mini.app/Frameworks/pythonA-charset_normal
> izer.md.framework/pythonA-charset_normalizer.md, 0
> x0002): tried: '/private/var/containers/Bundle/App
> lication/4C42D808-A658-4267-AB9C-EAC0B40240DF/a-Sh
> ell-mini.app/Frameworks/pythonA-charset_normalizer
> .md.framework/pythonA-charset_normalizer.md' (no s
> uch file), '/System/Library/Frameworks/pythonA-cha
> rset_normalizer.md.framework/pythonA-charset_norma
> lizer.md' (no such file)
> 
>
