### ISSUE TITLE
iOS 15 ready?

### ISSUE THREAD

**Issue by Maetran** [net00-1/SW-DLT#3]
Hey 
I have been using your SC long now. 
i am currently beta testing. 
it looks like some commands have been redesigned by Apple (I.e. „includes“, „starts with“)

Are you thinking about porting it to iOS 15 in the next weeks?

thanks 

BTW it looks like the update command is not working properly in iOS 15 PB3. An issue with the update link.

**Comment by net00-1** [comment]
I only have my main device where I test the shortcut, so I plan to update to iOS 15 when the stable version releases and then fix any issues that are out there.
