### ISSUE TITLE
about youtube download error

### ISSUE THREAD

**Issue by CHIHOLUEN** [net00-1/SW-DLT#30]
Hello, I am using iPhone 12 16.3.1. About 1 month ago when downloading YouTube videos, Exception Alert appeared. The download encountered an error. Try (if applicable) using the default quality, updating internal dependencies, or reviewing provided login details. If it is resolved?

**Comment by alkoka** [comment]
Same happened with me too. I've been using SW-DLT with the a-shell mini app and I couldn't download anything (iPhone XS Max, iOS 15.1).

A few days ago I deleted SW-DLT and the a-shell mini, downloaded the full version of a-shell and reinstalled SW-DLT.

Now it seems to be working fine. Make sure you try this too until a fix comes for a-shell mini. There seems to be something missing from the light version I guess.

**Comment by mmhverheijden** [comment]
Ran into the same issue lately, it fixed it for me by running following commands in the a-Shell terminal
```sh
pip install pip --upgrade
pip install yt-dlp --upgrade
pip install gallery-dl --upgrade
```
