### ISSUE TITLE
[Bug] gallery-dl broken

### ISSUE THREAD

**Issue by RevENGE-code** [net00-1/SW-DLT#31]
**Enviroment**
iOS 16.4.1 (20E252)
SW-DLT 3.18.1
a-Shell mini & a-Shell Version 1.11.1

**Describe the bug**
Whenever I try to download Images or Albums with the "Download Gallery"-option in SW-DLT, I get stuck in  "Process time depends on collection length". My phone gets warm, so it's doing something, but it never actually finishes nor download anything.

**Sample Link**
https://instagram.com/jason.noire?igshid=YmMyMTA2M2Y=
**Behavior**
[Screenshot](https://user-images.githubusercontent.com/54822494/230776748-68811117-ca23-4917-ad04-2d7bd64f5c94.jpeg) (stuck in an endless loop)

**Expected behavior**
process and download objects passed to Download Gallery-option of SW-DLT

**Edit**
I have tried to fix this by running the following in a shell-mini and a-Shell
```
pip install chardet
pip install yt-dlp --upgrade
pip install gallery-dl --upgrade
```
to no avail

**Comment by net00-1** [comment]
I noticed this issue yesterday when running tests for 3.18.2. For some reason the call to get output with `subprocess.getoutput()`  freezes. It's fixed on 3.18.2 by replacing it with `subprocess.check_output()` which is more recommended. I'll push the update shortly.
