### ISSUE TITLE
Get dictionary value failed because shortcuts couldnt convert deom Text to Dictionary 

### ISSUE THREAD

**Issue by dvtkrlbs** [net00-1/SW-DLT#33]
Having this issue with tiktok 
![IMG_2798](https://user-images.githubusercontent.com/24792168/231073034-f8fcc513-9490-4f9b-b0b5-059a45b42862.jpeg)

**Comment by net00-1** [comment]
Does it happen with any tiktok link? can you share one to test?

**Comment by abdulwaheedsyed** [comment]
Add this and it will work:
![sw-dlt-fix](https://user-images.githubusercontent.com/9998230/236240811-a049505a-b984-4029-9df9-274123ff4919.jpg)

Tested with TikTok, Instagram, Youtube & Reddit. Working 👍

**Comment by net00-1** [comment]
Thanks, I will add this on the next update
