### ISSUE TITLE
there is a problem with “yt-dls” package

### ISSUE THREAD

**Issue by mahdiarfrm** [net00-1/SW-DLT#34]
hey
hope you doin fine

there is a problem with yt-dls package when downloading p0rn videos is happening 

is there a solution?
i tried couple of things but didn’t work
iPhone 13 iOS 16.4.1 a-Shell mini

![IMG_4465](https://github.com/net00-1/SW-DLT/assets/29659769/4feadc89-76d5-4386-90fd-0faa2a0f7ce9)

**Comment by net00-1** [comment]
Have you tried [these steps](https://github.com/net00-1/SW-DLT/blob/master/Docs.md#updating-utilities)? I'm planning to make it automatic in the future but right now it has to be manual
