### ISSUE TITLE
No more videos downloaded

### ISSUE THREAD

**Issue by LonelyLoon** [net00-1/SW-DLT#35]
Hi

I'm using SW-DLT on my iPhone on a daily base to download audio and video files and forward them to my podcast app (iCatcher). A few weeks ago, SW-DLT stopped working, so I deleted the dependencies. This worked fine for audio files, but not really for videos.

Before it stopped working (and I deleted the dependencies), iOS showed my the video which I could then forward to whereever. Now there's no more video shown; only a message on the screen that **says** that a video **had been downloaded**. However, when I forward it to iCatcher, only audio is transmitted.

Is this a problem with the SW-DLT shortcut or with iOS? Or am I the problem? :) (Sorry, no developer here, just a great fan of SW-DLT)

**Comment by net00-1** [comment]
Can you please share a link that is giving you issues? that way I can take a closer look at what might be happening. Also sorry for late reply

**Comment by LonelyLoon** [comment]
Hello

Looks like I missed an Update of SW-DLT (?). In the process of answering 
to your e-mail I re-downloaded SW-DLT, and now everything works fine.

Sorry for the trouble and thanks
Andreas
