### ISSUE TITLE
Conversion error: Get Dictionary Value failed because Shortcuts couldn't convert from Text to Dictionary.

### ISSUE THREAD

**Issue by glottisfaun0000** [net00-1/SW-DLT#36]
I’ve tried sw-dlt a couple times in the past but always come back to getting stuck on this error. Is there any fix?

Happens on `Get Value for output_code in 🔗decodedProps` after `Url Decode Shortcut Input`

**Comment by net00-1** [comment]
Can you share a link that returns this error?

**Comment by glottisfaun0000** [comment]
I just took a closer look at it and this was happening with anything I threw at the shortcut.

**For now, reinstalling a-shell Mini after doing a full uninstall with documents & data from Settings > General > iPhone Storage has SW-DLT working again.** 

Thanks for getting back to me, hope this solution sticks and can help anyone else who runs into this issue.

**Comment by glottisfaun0000** [comment]
Reopening - I was completely wrong about what was happening here. I get the conversion error whenever sharing a Tiktok link (which yt-dlp fully supports) to the shortcut from the share menu. But copying to clipboard, setting SW-DLT t- check clipboard, and running from Shortcuts manually works fine.

Example link: https://www.tiktok.com/@allthethingsmarine/video/7271337115437255978
Open in Safari (or tiktok app)
Share sheet > SW-DLT
Get `Conversion error: Get Dictionary Value failed because Shortcuts couldn't convert from Text to Dictionary.`

Not sure what other info I can provide to help but I do notice that this also happens when sharing a [Proxitok](https://github.com/pablouser1/ProxiTok) link to the shortcut. yt-dlp uses the generic extractor for proxitok rather than the built-in Tiktok extractor, so maybe it's something in common to both original Tiktok and the alternative Proxitok urls? Let me know if I can check anything else.
Proxitok example link: https://proxitok.pussthecat.org/@allthethingsmarine/video/7271337115437255978

**Comment by glottisfaun0000** [comment]
I found another scenario with similar behavior. If a YouTube short is open in Safari and shared to SW-DLT from the Safari share menu button, you get the Conversion error. Example url: https://m.youtube.com/shorts/UWd_3FxoJXw

But using the share button on the page gives a different url which works fine with SW-DLT. Same url shared from in the YouTube page window: https://youtube.com/shorts/UWd_3FxoJXw?si=11lO1S7oJjisGkdj

The weird thing is that copying and pasting the first url turns it into the second form, which is what SW-DLT receives if I copy to clipboard and pass it to the shortcut manually. I get the m.youtube url from the Safari address bar or if I share it to another shortcut, so I'm assuming that's what SW-DLT gets from the share sheet in the first case. Hope this helps.

**Comment by net00-1** [comment]
Thanks for the link, I will test them!

**Comment by glottisfaun0000** [comment]
Ok, here's another one that makes me think it's _not_ a url structure issue. Any twitter post with media shared to SW-DLT from the browser (Safari bottom bar icon) share sheet gives the Conversion error. Example url: https://twitter.com/NPR/status/1646138100035272704
And for me the url is identical in the address bar, copied, etc. Using the share button below post > `Share post via ...` in the twitter webapp itself to share to SW-DLT from that share sheet does work. So weird. Maybe something to do with the URL vs Article distinction that shortcuts makes?

**Comment by net00-1** [comment]
I have released v3.19 which hopefully fixes some instances of these errors, however I have not been able to reliably reproduce it to know the real reason, so I'm leaving this open for now. 

Does anyone else have links they can share that consistently give this error? Please add the following details:

- iOS version
- Link
- Which options you used (fps, resolution, etc)

**Comment by glottisfaun0000** [comment]
iOS Version: 17.0.3

Example link: https://www.tiktok.com/t/ZT8DHDB8m/

Steps to reproduce:
1. Open above link/video in [Tiktok App](https://apps.apple.com/us/app/tiktok/id835599320)
2. Tap share ↗️ arrow in lower right corner
3. In second row of share options scroll to the end and tap `... More` for system Share Sheet
4. In Share Sheet tap SW-DLT shortcut
5. Before any options appear, "Conversion error" appears and ends the shortcut.

**Comment by net00-1** [comment]
It's interesting that it happens before you can even choose what to download. Can you check if this version works?

https://www.icloud.com/shortcuts/29d5c77bfec64d23947bdc849fa047a6

**Comment by ksj01** [comment]
> It's interesting that it happens before you can even choose what to download. Can you check if this version works?
> 
> https://www.icloud.com/shortcuts/29d5c77bfec64d23947bdc849fa047a6

This version worked for me! Didn’t try the one from a few days before. Thank you so much!

**Comment by net00-1** [comment]
Thanks for checking, this tells me that the issue is caused by actions not failing silently as expected. Apparently they now stop the shortcut.

I will include the fix in the next update (anyone using the above version should have no issue getting the update).
