### ISSUE TITLE
New Twitter (X) not working

### ISSUE THREAD

**Issue by matthiasballreich** [net00-1/SW-DLT#37]
Since some weeks SW-DLT isn't working with the new Twitter (X).
I tried to reset the libraries and depencies, but has no effect.

Here a sample url: https://x.com/mccrushi/status/1696876940550971448?s=46&t=ivbqimqKkpGyL345eQ2_QA

**Comment by kawnnor** [comment]
‌‌yt-dlp has been updated and can now download videos from new Twitter (X).

**Comment by matthiasballreich** [comment]
look you're right. I tested it and now it works. So i close this ticket and hope it will continue to work ;)
