### ISSUE TITLE
Couldn’t  run , choose from list  error message 

### ISSUE THREAD

**Issue by Jeremyezerzer** [net00-1/SW-DLT#4]
Hi everyone 
Super noob here 
I’ve used SW-DLT for many months on iOS 14 and recently had to format phone. 
I’ve downloaded recent update but it doesn’t go forward at all even with both shells ( a-shell and a-shell mini installed). I get the same message over again (couldn’t run, “choose from list” this action could not run because he runner quit unexpectedly.  It also got to the script “rename” but it never gives any other message or error.  
help me out? 
thank you :) 
![3CFDF3D4-78B6-4CF9-B98D-E51D0FF9BBBB](https://user-images.githubusercontent.com/88303999/127806154-cb8d7146-933e-4ff1-8674-4c14bb64260e.png)

**Comment by Jeremyezerzer** [comment]
for dork reason it always stops jeremyezerzer@gmail.com and gives me that error when running. 
not sure if this helps. I’m 

![9C5D6B01-CD59-4E9E-A00D-3837D299DB40](https://user-images.githubusercontent.com/88303999/127806726-2eb243fc-da86-4e4f-b80b-9698895365da.png)

**Comment by net00-1** [comment]
This is an error with the Shortcuts App itself, it's usually temporary but if it always happens for you then try to:

- Reboot the device
- Uninstall/reinstall the shortcuts app (make sure your shortcuts are backed up first)
- Delete SW-DLT and get the latest version from routinehub.
