### ISSUE TITLE
[Question] Does downloading without logging in result in lower quality images/videos

### ISSUE THREAD

**Issue by Wrestor** [net00-1/SW-DLT#40]
Hey net00-1, 

Thanks for maintaining this awesome shortcut. Is SW-DLT (in this case gallery-dl) able to archive the same high quality downloads as [Instagram Download from Gluebyte](https://routinehub.co/shortcut/7823/) when logging in?

**Comment by net00-1** [comment]
I did some digging, and for high resolution images both shortcuts appear to provide the same results. However it doesn't seem that yt-dlp or gallery-dl are able to download a 60fps reel (even when authenticating in both tools). Instagram Download appears to be custom-made for this.
