### ISSUE TITLE
JSON error when downloading videos from TikTok

### ISSUE THREAD

**Issue by busti** [net00-1/SW-DLT#51]
![image](https://github.com/net00-1/SW-DLT/assets/3575167/56fa65c9-d727-476c-a683-21bb16dc8a46)

**Comment by net00-1** [comment]
I am able to download videos from Tiktok. So to take another look at this please confirm you have [updated versions of yt-dlp/gallery-dl](https://github.com/net00-1/SW-DLT/blob/master/Docs.md#updating-utilities). If the error continues share the link that you are using.
