### ISSUE TITLE
A-SHELL sometimes opens and just stays on a blinking cursor

### ISSUE THREAD

**Issue by AtariBaby** [net00-1/SW-DLT#8]
Hi

iPadOS 15.1.1, iPad Pro 2nd gen. Also on iOS 15.1.1, iPhone 13 Pro

Firstly, I realize this is halted, so forgive me if you don’t want to hear about it! But in the event it’s good to have an issue documented for the future…

But I thought I would mention that with some frequency, if I activate SWDLT, it opens A-shell (full version), but instead of performing operations, it just sits with a blinking cursor, and nothing happens. I think this happens if it was open within a recent period of time. If I force quit A-Shell and do it again, then it fires up all the commands.

So possibly the solution would be to have SW-DLT quit the app, if that’s possible?

By the way, this is easily just about the best shortcut I’ve ever used. Thank you!

**Comment by net00-1** [comment]
Thanks, yes this is paused until there's more news about `youtube-dl` (I know `yt-dlp` is out there, but it doesn't fully work in a-Shell yet)

As for this issue, I have seen some times where a-Shell doesn't start the script and it just does nothing. I'll investigate what could be wrong here, or any workaround possible.

**Comment by net00-1** [comment]
I definitely have seem this issue, but I can't reproduce it enough to pinpoint the cause. It could be very well coming from the a-shell app.
